### ISSUE TITLE
Can't get width or height of an Image

### ISSUE THREAD

**Issue by hazzard993** [lino-levan/raylib-deno#2]
### Repro

```ts
import { Image } from "./raylib-deno/mod.ts";

const image = Image.load("ray.png");
console.log(image.width);
```

Image I'm loading: ![ray](https://github.com/user-attachments/assets/8bf95aab-37d7-46de-816a-a65f57e654f4)

Run with `deno run --allow-env --allow-write --allow-read --allow-ffi --unstable-ffi .\bug.ts`

### Expected result

```
16
```

### Actual result

```
INFO: FILEIO: [ray.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (16x16 | R8G8B8A8 | 1 mipmaps)
error: Uncaught (in promise) TypeError: First argument to DataView constructor must be an ArrayBuffer
    const view = new DataView(this.#buffer);
                 ^
    at new DataView (<anonymous>)
    at Image.get width (file:///project/deno-raylib/raylib-deno/src/image.ts:26:18)
    at file:///C:/project/deno-raylib/bug.ts:4:21
    at eventLoopTick (ext:core/01_core.js:168:7)
```

### Workaround

`this.#buffer` seems to be a `Uint8Array`, not an `ArrayBuffer` which is what `DataView` wants

So I switched `this.#buffer` from an `ArrayBuffer` to `Uint8Array` and did this for `get width()` and `get height()`

```diff
- const view = new DataView(this.#buffer);
+ const view = new DataView(this.#buffer.buffer);
```

**Comment by lino-levan** [comment]
Yep, this looks like a bug. Are you willing to submit a PR for it?
